# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases\192.168.33.5_test_test.json
import logging
logging.basicConfig(encoding='utf-8-sig')
import loguru
import sys
sys.path.insert(0,"C:\Python311\Scripts")
sys.path.insert(0,"C:\Python311\lib\site-packages")
from httprunner import Config, HttpRunner, RunRequest, Step


class TestCaseT192168335TestTest(HttpRunner):

    config = Config("testcase description").variables(
        **{
            "connect_sid": "${get_connect_sid()}",
            "headers_cookie": "${get_headers_cookie()}",
        }
    )

    teststeps = [
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/default")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Cache-Control": "max-age=0",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-None-Match": 'W/"aa34-HsGmM39aySXStn2EgbQKrg+ckP8"',
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/html; charset=utf-8",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/mobiscroll.css")
            .with_params(**{"v": "1"})
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"3256-1858122eefc"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/validateCode")
            .with_headers(
                **{
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "image/bmp",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/jquery-1.10.2.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"16bb3-1858122ef1c"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/html5shiv.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"97d-1858122ef1b"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/respond.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"fcf-1858122ef1f"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/md5.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"2465-1858122ef25"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/common.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Mon, 16 Jan 2023 03:50:05 GMT",
                    "If-None-Match": 'W/"8ef5-185b8b2d1c8"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/font-awesome/fonts/fontawesome-webfont.woff"
            )
            .with_params(**{"v": "4.1.0"})
            .with_headers(**{"Referer": ""})
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "font/woff",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/themes/style1/bj.jpg")
            .with_headers(**{"Referer": ""})
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "image/jpeg",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/themes/style1/bj.jpg")
            .with_headers(**{"Referer": ""})
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "image/jpeg",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/validateCode")
            .with_params(**{"d": "0.9577218888578622"})
            .with_headers(
                **{
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "image/bmp",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/images/favicon/favicon.ico")
            .with_headers(
                **{
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"10be-1858122ef0c"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .post("http://192.168.33.5:9100/login")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Content-Length": "75",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Host": "192.168.33.5:9100",
                    "Origin": "http://192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .with_data(
                {
                    "count": "0",
                    "name": "guanli",
                    "password": "03f9aeef097033d251225d1247f9dd65",
                    "validateCode": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/plain",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/default")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-None-Match": 'W/"1e5a-EQCdxbbRttrGkTxwuv3UHh9ZtMQ"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/html; charset=utf-8",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/mobiscroll.css")
            .with_params(**{"v": "1"})
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"3256-1858122eefc"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/images/pic.png")
            .with_headers(
                **{
                    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"974-1858122ef0d"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/jquery-1.10.2.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"16bb3-1858122ef1c"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/jquery-migrate-1.2.1.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"1c1f-1858122ef1c"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap/js/bootstrap.min.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"7c09-1858122ef3c"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"c90-1858122ef38"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/html5shiv.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"97d-1858122ef1b"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/respond.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"fcf-1858122ef1f"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/metisMenu/jquery.metisMenu.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"8e2-1858122ef55"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/slimScroll/jquery.slimscroll.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"34de-1858122ef59"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/jquery-cookie/jquery.cookie.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"bfa-1858122ef50"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/iCheck/icheck.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"1343-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/iCheck/custom.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"854-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/jquery-notific8/jquery.notific8.min.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"d37-1858122ef53"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/jquery.menu.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"fb7-1858122ef1e"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/holder/holder.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"3087-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/responsive-tabs/responsive-tabs.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"136d-1858122ef59"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/jquery-news-ticker/jquery.newsTicker.min.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"e53-1858122ef53"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/moment/moment.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"197d9-1858122ef56"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap-datepicker/js/bootstrap-datepicker.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"b6e5-1858122ef37"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap-daterangepicker/daterangepicker.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"85b5-1858122ef38"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"594d-1858122ef38"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/common.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Mon, 16 Jan 2023 03:50:05 GMT",
                    "If-None-Match": 'W/"8ef5-185b8b2d1c8"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/usersgrant.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"32e-1858122ef34"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/main.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"482f-1858122ef1e"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/welcome")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-None-Match": 'W/"3f8-IvHq3hsdm3sOMT/ifKheMfPwBBk"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/font-awesome/fonts/fontawesome-webfont.woff"
            )
            .with_params(**{"v": "4.1.0"})
            .with_headers(**{"Referer": ""})
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "font/woff",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/animate.css/animate.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"feea-1858122ef37"',
                    "Referer": "http://192.168.33.5:9100/welcome",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"61c-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/welcome",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/themes/style1/pink-violet.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"341c6-1858122ef04"',
                    "Referer": "http://192.168.33.5:9100/welcome",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/css/style-responsive.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"1f6f-1858122eefc"',
                    "Referer": "http://192.168.33.5:9100/welcome",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/getCurPageGrant")
            .with_params(**{"powerid": ""})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/default",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/plain",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/iCheck/skins/minimal/all.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"3467-1858122ef43"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/iCheck/skins/square/all.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"33d8-1858122ef43"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/iCheck/skins/flat/all.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"2dae-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/iCheck/skins/line/all.css")
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"4736-1858122ef43"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/iCheck/skins/polaris/polaris.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"52e-1858122ef43"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/iCheck/skins/futurico/futurico.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"4be-1858122ef42"',
                    "Referer": "http://192.168.33.5:9100/resource/vendors/iCheck/skins/all.css",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/winAndLoseReport")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-None-Match": 'W/"2364-cG00V3ePlPoiCVddKheC5XWUgEk"',
                    "Referer": "http://192.168.33.5:9100/default",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/datepicker/jquery.datetimepicker.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"264a-1858122ef3f"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap/js/bootstrap-table.css"
            )
            .with_headers(
                **{
                    "Accept": "text/css,*/*;q=0.1",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"1c7f-1858122ef3b"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/js/jquery-1.10.2.min.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"16bb3-1858122ef1c"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap/js/bootstrap.min.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"7c09-1858122ef3c"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/vendors/moment/moment.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"197d9-1858122ef56"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap/js/bootstrap-table.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"1afd9-1858122ef3c"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/bootstrap/js/bootstrap-table-zh-CN.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"4cd-1858122ef3b"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/datepicker/jquery.datetimepicker.js"
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"cb21-1858122ef3f"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/common.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Mon, 16 Jan 2023 03:50:05 GMT",
                    "If-None-Match": 'W/"8ef5-185b8b2d1c8"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/usersgrant.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Thu, 05 Jan 2023 08:53:48 GMT",
                    "If-None-Match": 'W/"32e-1858122ef34"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/resource/sysmanage/winandlosereport.js")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "If-Modified-Since": "Mon, 16 Jan 2023 03:50:05 GMT",
                    "If-None-Match": 'W/"4b72-185b8b2d1cb"',
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 304, "assert response status code")
        ),
        Step(
            RunRequest("")
            .get(
                "http://192.168.33.5:9100/resource/vendors/font-awesome/fonts/fontawesome-webfont.woff"
            )
            .with_params(**{"v": "4.1.0"})
            .with_headers(**{"Referer": ""})
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "font/woff",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/getCurPageGrant")
            .with_params(**{"powerid": "81"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/plain",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/winAndLoseReport/getGameType1")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/plain;charset=utf-8",
                "assert response header Content-Type",
            )
        ),
        Step(
            RunRequest("")
            .get("http://192.168.33.5:9100/winAndLoseReport/InitData")
            .with_params(
                **{
                    "GameUserNO": "",
                    "RoomType": "",
                    "_": "1674106333494",
                    "accounts": "",
                    "beginDate": "",
                    "endDate": "",
                    "kindId": "",
                    "limit": "20",
                    "offset": "0",
                    "serverId": "",
                    "total": "0",
                }
            )
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json",
                    "Host": "192.168.33.5:9100",
                    "Referer": "http://192.168.33.5:9100/winAndLoseReport",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(**{"connect.sid": "$connect_sid"})
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/plain;charset=utf-8",
                "assert response header Content-Type",
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseT192168335TestTest().test_start()
